name: Continuous Integration

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    pull-requests: write
    contents: write

env:
    PYTHON_VERSION: "3.12"

jobs:
    build-and-test:
        name: continuous-integration
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true

            - name: Run pre-commit hooks (optional)
              run: |
                  uv pip install --system pre-commit
                  pre-commit run --all-files || true
              continue-on-error: true

            - name: Install and sync dependencies
              run: |
                  uv sync --locked --all-extras
